# Generated by Django 2.2 on 2019-04-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='phtot_url',
            new_name='photo_url',
        ),
    ]
